language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist

script:
  - composer test